import { UserProvider } from "@/providers/UserProvider";
import Header from "./Header";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "./Footer";
import AppProvider from "./provider";

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <AppProvider>
          <UserProvider>
            <Header />
            {children}
            <Footer />
          </UserProvider>
        </AppProvider>
      </body>
    </html>
  );
}
