import { UserProvider } from "@/providers/UserProvider";
import Header from "./Header";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <UserProvider>
          <Header />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
